### PR TITLE
Force fp32 during accumulation pass on Intel

### PR DESCRIPTION
**Pull request by lastquest**
fp16 accumulation is creating dark artifacts on Intel GPUs, possibly related to a clamping issue

### CODE REVIEW

**Comment by lastquest** [comment]
Corruption on the fp16 path has been addressed in the Intel driver but I suggest to compile the Accumulation pass turning on the precise qualifier (/Gis)
https://github.com/Microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#precise-qualifier
since the kernel is doing fp16 trig functions (sin, cos) and it is not safe to allow for re-association of the instructions using those outputs.

**Comment by hsiversson** [comment]
@lastquest 
Which Intel driver version addressed this issue?
I'm seeing the same issue currently on the November public driver (31.0.101.3802).

**Comment by lastquest** [comment]
Hi @hsiversson ! The public driver with that fix should be available soon, and go public this week (~12/7/2022) , version .3951.
Please let me know if you have still have issues with FSR2 on Intel GPUs with that driver, I can follow up with you.

**Comment by lastquest** [comment]
BETA driver with the fix is public (3959):
https://www.intel.com/content/www/us/en/download/729157/intel-arc-graphics-windows-dch-driver-beta.html

**Comment by hsiversson** [comment]
@lastquest Thank you for the update, I'll try it out!

**Pull request closed without merging**
